name: BlazinJoin
main: iiFlamiinBlaze\BlazinJoin\BlazinJoin
description: An advanced join enhancement plugin!
version: 1.1.6
api: 3.0.0
author: iiFlamiinBlaze
load: POSTWORLD
commands:
 blazinjoin:
  description: BlazinJoin command which allows you to edit the config easily
  permission: blazinjoin.command
permissions:
 blazinjoin.command:
  default: op